const Listcard = [
  {
    code: 1,
    className: "contain",
    title: "Help & information",
    first: "Track Order",
    second: "Delivery",
    third: "Return Order",
    four: "FAQs",
  },
  {
    code: 2,
    className: "contain sec",
    title: "About Supro",
    first: "About us",
    second: "Careers",
    third: "Corporate",
    four: "Investors",
  },
  {
    code: 3,
    className: "contain third",
    title: "Online Shop",
    first: "Shoes",
    second: "Bags",
    third: "Wallets",
    four: "belts",
  },
  {
    code: 4,
    className: "contain extra",
    title: "Language",
    first: "English",
    second: "",
    third: "",
    four: "",
  },
  {
    code: 5,
    className: "contain extra",
    title: "Currency",
    first: "USD",
    second: "",
    third: "",
    four: "",
  },
];
export default Listcard;
